# glide configuration is specified in this file. 
# Variable formatting follows national gdlier DAC netCDF format version 2
# https://ioos.github.io/glider-dac/ngdac-netcdf-file-format-version-2

# Dashes indicate separate yaml documents. The ordering of documents is important. 

--- ### PART 1 GLOBAL CONFIGURATION

time_start: 2000-01-01T00:00:00
time_end: 2040-01-01T00:00:00

--- ### PART 2 VARIABLE DEFINITIONS, QC CONTROLS, AND METADATA

# TIME VARIABLES

time: # This is the name the we want
  # This list of sources can only be done for variables that do not appear in the same file
  # because we are essentially mapping one variable name, time, to two other variable names.
  source: ["m_present_time", "sci_m_present_time"]
  track_qc: True
  # conversion: posix_to_datetime
  CF: # CF attributes here
    long_name: Time
    standard_name: time
    calendar: gregorian
    units: seconds since 1970-01-01T00:00:00Z
    axis: T
    observation_type: "measured"

# FLIGHT VARIABLES

lat: # This is the name that we want
  source: m_lat  # This is the name that Slocum gliders use
  conversion: dpm_to_dd  # Function applied to convert data units
  interpolate_missing: True  # Interpolating nan values
  max_gap: 600  # Max gap in seconds over which to interpolate nan values
  track_qc: True  # Whether to keep track of quality control
  CF: 
    long_name: Latitude
    standard_name: latitude
    units: degrees_north
    axis: Y
    comment: "Estimated between surface fixes"
    observation_type: measured
    platform: platform
    reference: WGS84
    valid_max: 90.0
    valid_min: -90.0
    coordinate_reference_frame: urn:ogc:crs:EPSG::4326

lon:
  source: m_lon
  conversion: dpm_to_dd
  interpolate_missing: True
  max_gap: 600
  track_qc: True
  CF:
    long_name: Longitude
    standard_name: longitude
    units: degrees_east
    axis: X
    comment: "Estimated between surface fixes"
    observation_type: measured
    platform: platform
    reference: WGS84
    valid_max: 180.0
    valid_min: -180.0
    coordinate_reference_frame: urn:ogc:crs:EPSG::4326

m_gps_lat:
  source: m_gps_lat
  conversion: dpm_to_dd
  drop_from_l2: True  # Not included into l2 dataset if true
  CF: 
    long_name: Latitude
    standard_name: latitude
    units: degrees_north
    axis: Y
    comment: "Surface fixes"
    observation_type: measured
    platform: platform
    reference: WGS84
    valid_max: 90.0
    valid_min: -90.0
    coordinate_reference_frame: urn:ogc:crs:EPSG::4326

m_gps_lon:
  source: m_gps_lon
  conversion: dpm_to_dd
  drop_from_l2: True
  CF:
    long_name: Longitude
    standard_name: longitude
    units: degrees_east
    axis: X
    comment: "Surface fixes"
    observation_type: measured
    platform: platform
    reference: WGS84
    valid_max: 180.0
    valid_min: -180.0
    coordinate_reference_frame: urn:ogc:crs:EPSG::4326

heading:
  source: m_heading
  conversion: rad_to_deg
  interpolate_missing: True
  CF:
    long_name: Heading
    standard_name: platform_orientation
    units: degrees
    observation_type: measured
    valid_max: 360.0
    valid_min: 0.0

pitch: 
  source: m_pitch
  conversion: rad_to_deg
  interpolate_missing: True
  CF:
    long_name: Pitch
    standard_name: platform_pitch_fore_up
    units: degrees
    observation_type: measured
    valid_max: 180.0
    valid_min: -180.0

roll:
  source: m_roll 
  conversion: rad_to_deg
  interpolate_missing: True
  CF:
    long_name: Roll
    standard_name: platform_roll_starboard_down
    units: degrees
    observation_type: measured
    valid_max: 180.0
    valid_min: -180.0

m_depth:
  source: m_depth
  drop_from_l2: True
  CF:
    long_name: Depth
    standard_name: depth
    units: m
    valid_min: 0.0
    valid_max: 2000.0
    positive: "down"
    reference_datum: "sea-surface"
    instrument: "instrument_ctd"
    observation_type: "measured"
    
# SCIENCE VARIABLES

pressure: 
  source: sci_water_pressure
  conversion: bar_to_dbar
  interpolate_missing: True
  track_qc: True
  CF: 
    long_name: Pressure
    standard_name: sea_water_pressure
    units: dbar
    valid_min: 0.0
    valid_max: 2000.0
    positive: "down"
    reference_datum: "sea-surface"
    instrument: "instrument_ctd"
    observation_type: "measured"
    accuracy: 1.0
    precision: 2.0
    resolution: 0.02
    comment: "ctd pressure sensor"

conductivity:
  source: sci_water_cond
  interpolate_missing: True
  track_qc: True
  CF:
    long_name: Conductivity
    standard_name: sea_water_electrical_conductivity
    units: S m-1  # Not converted to mS cm-1 becase we need S m-1 for glider DAC
    instrument: instrument_ctd
    valid_min: 0.1
    valid_max: 10.
    observation_type: "measured"
    accuracy: 0.0003
    precision: 0.0001
    resolution: 0.00002

temperature:
  source: sci_water_temp
  interpolate_missing: True
  track_qc: True
  CF:
    long_name: Temperature
    standard_name: sea_water_temperature
    units: celsius
    instrument: instrument_ctd
    valid_min: -5.0
    valid_max: 50.0
    observation_type: "measured"
    accuracy: 0.002
    precision: 0.001
    resolution: 0.0002

# CALCULATED VARIABLES

salinity:
  track_qc: True
  CF:
    # accuracy:
    instrument: instrument_ctd
    long_name: Salinity
    observation_type: calculated
    platform: platform
    # precision:
    # resolution:
    standard_name: sea_water_practical_salinity
    units: 1
    valid_max: 40.0
    valid_min: 0.0

density:
  track_cq: True
  CF: 
    # accuracy:
    instrument: instrument_ctd
    long_name: Density
    observation_type: calculated
    platform: platform
    # precision:
    # resolution:
    standard_name: sea_water_density
    units: kg m-3
    valid_max: 1040.0
    valid_min: 1015.0

rho0:
  track_cq: True
  CF: 
    # accuracy:
    instrument: instrument_ctd
    long_name: Potential density
    observation_type: calculated
    platform: platform
    reference_pressure: 0
    # precision:
    # resolution:
    standard_name: sea_water_density
    units: kg m-3
    valid_max: 1040.0
    valid_min: 1015.0

SA:
  track_qc: True
  CF:
    # accuracy:
    instrument: instrument_ctd
    long_name: Absolute salinity
    observation_type: calculated
    platform: platform
    # precision:
    # resolution:
    standard_name: sea_water_absolute_salinity
    units: g kg-1
    valid_max: 40.0
    valid_min: 0.0

CT:
  track_qc: True
  CF:
    long_name: Conservative temperature
    standard_name: sea_water_conservative_temperature
    units: celsius
    instrument: instrument_ctd
    valid_min: -5.0
    valid_max: 50.0
    observation_type: calculated
    # accuracy: 0.002
    # precision: 0.001
    # resolution: 0.0002

N2:
  track_qc: True
  CF:
    long_name: Buoyancy frequency squared
    standard_name: square_of_brunt_vaisala_frequency_in_sea_water
    units: s-2
    observations_type: calculated

depth:
  track_qc: True
  CF:
    long_name: Depth
    standard_name: depth
    units: m
    valid_min: 0.0
    valid_max: 2000.0
    positive: "down"
    reference_datum: "sea-surface"
    instrument: "instrument_ctd"
    observation_type: "calculated"

z:
  track_qc: True
  CF:
    long_name: Height
    standard_name: height
    units: m
    valid_min: 0.0
    valid_max: -2000.0
    positive: "up"
    reference_datum: "sea-surface"
    instrument: "instrument_ctd"
    observation_type: "calculated"

# ASSIMILATED VARIABLES

e_1: 
  CF: 
    long_name: TKE dissipation rate
    standard_name: specific_turbulent_kinetic_energy_dissipation_in_sea_water
    comment: Estimated using shear probe 1
    units: W kg-1
    valid_min: 0.0
    valid_max: 0.001
    instrument: "instrument_microrider"
    observation_type: "calculated"

e_2: 
  CF: 
    long_name: TKE dissipation rate
    standard_name: specific_turbulent_kinetic_energy_dissipation_in_sea_water
    comment: Estimated using shear probe 2
    units: W kg-1
    valid_min: 0.0
    valid_max: 0.001
    instrument: "instrument_microrider"
    observation_type: "calculated"